export interface Ticket2 {
    amount_igtf: number,
    bill_datetime_long: number,
    bill_datetime_string: string,
    total: number,
    subtotal: number,
    net_price: number,
    tax_value: number,
    bill_id: number,
    bill_number: number,
    fact_notec: number,
    fiscal_printer_serial: string,
    station_bill_id: number,
    type_doc: string,
    customer_identification: number,
    customer_name: string,
    customer_address: string,
    customer_id: number
    customer_phone: string
    customer_type: string
    tips: number
    discount: number
    exchange_date_day: number
    product_total: number
    product_net_price: number
    product_subtotal: number
    product_discount: number
    product_tax_value: number
    product_stock: number
    quantity: number
    product_name: string
    family_code: number
    family_name: string
    product_type_name: string
    product_type_code: number
    product_code: number
    sale_price_1: number
    sale_price_2: number
    product_sale_price: number
    product_bar_code: number
    product_uoms_name: string
    order_id: number
    sale_voucher: number
    service_value: number
    status: string
    suborder_id: number
    tax_id: number
    station_name: string
    journal_end: number
    journal_id: number
    journal_start: number
}